// images here are imported through the imagesSkills folder in the public folder 
export const IMAGE_DATA = [
    { name: 'HTML', src: '/imagesSkills/html.svg'},
    { name: 'MongoDB', src: '/imagesSkills/mongo.svg'},
    { name: 'AWS', src: '/imagesSkills/aws.svg'},
    { name: 'CSS', src: '/imagesSkills/css.svg'},
    { name: 'Express', src: '/imagesSkills/express.svg'},
    { name: 'GIT', src: '/imagesSkills/git.svg'},
    { name: 'Java', src: '/imagesSkills/java.svg'},
    { name: 'JavaScript', src: '/imagesSkills/js.svg'},
    { name: 'MySQL', src: '/imagesSkills/mysql.svg'},
    { name: 'NextJS', src: '/imagesSkills/next.svg'},
    { name: 'NodeJS', src: '/imagesSkills/node.svg'},
    { name: 'PHP', src: '/imagesSkills/php.svg'},
    { name: 'React', src: '/imagesSkills/react.svg'},
    { name: 'Ruby', src: '/imagesSkills/ruby.svg'},
    { name: 'SQL', src: '/imagesSkills/sql.svg'},
    { name: 'Kubernetes', src: '/imagesSkills/kubernetes.svg'},
    { name: 'Docker', src: '/imagesSkills/docker.svg'},
    { name: 'Canva', src: '/imagesSkills/canva.svg'},
    { name: 'Figma', src: '/imagesSkills/figma.svg'},
    { name: 'TypeScript', src: '/imagesSkills/ts.svg'},
  ];